#SET group_concat_max_len = 50000;

#SELECT group_concat(Social_Media) , Nom
#FROM ivi_masterdata_covid19.masterdata GROUP BY Nom ORDER BY Nom;


#SELECT distinct GROUP_CONCAT(Social_Media), nom, COUNT(*)  c FROM masterdata GROUP BY nom HAVING c > 1;

#SELECT COUNT( DISTINCT Nom, Social_Media)  FROM masterdata WHERE Social_Media LIKE 'Facebook';


SELECT COUNTRY, COUNT( DISTINCT NOM, COUNTRY) FROM MASTERDATA GROUP BY COUNTRY;

SELECT SOCIAL_MEDIA, COUNT( DISTINCT NOM, SOCIAL_MEDIA) FROM MASTERDATA GROUP BY SOCIAL_MEDIA;

SELECT USAGE_PURPOSE, COUNT( DISTINCT NOM, USAGE_PURPOSE) FROM MASTERDATA GROUP BY USAGE_PURPOSE;

SELECT PROBLEMS_OCCUR, COUNT( DISTINCT NOM, PROBLEMS_OCCUR) FROM MASTERDATA GROUP BY PROBLEMS_OCCUR;

SELECT COST_INCREAMENTS, COUNT( DISTINCT NOM, COST_INCREAMENTS) FROM MASTERDATA GROUP BY COST_INCREAMENTS;

SELECT Psychological_Problem, COUNT( DISTINCT NOM, Psychological_Problem) FROM MASTERDATA GROUP BY Psychological_Problem;



masterdata